from typing import List

from ..models import Cortex


class CortexManager:
    def __init__(self) -> None: ...

    def register_cortex(self, cortex: Cortex) -> None: ...

    def update_cortex(self, cortex: Cortex) -> None: ...

    def unregister_cortex(self, cortex: Cortex) -> None: ...

    def list_cortices(self) -> List[Cortex]: ...
